apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Release.Name}}--deployment
 namespace: default
spec:
 selector:
   matchLabels:
     app: spring-music
 replicas: 1
 template:
   metadata:
     labels:
       app: spring-music
       version: "1.0"
   spec:
     containers:
     - name: music
       image: {{.Values.containers.repo}}/{{.Values.containers.image}}:{{.Values.containers.tag}}
       ports:
       - containerPort: {{ .Values.containers.port }}
       env:
        - name: DBNAME
          valueFrom:
                  configMapKeyRef:
                          name: {{ .Release.Name }}-configmap
                          key: dbname
